# This is given as a sample, you should probably create your own in production
version: '3'

services:
  mongo:
    image: mongo:4
    restart: always
    networks:
      - internal
    volumes:
      - mongo:/data/db:rw

  redis:
    image: redis:4-alpine
    restart: 'always'
    networks:
      - internal

  client:
    image: lolpants/beatsaver-reloaded:client-latest
    build: client
    restart: always
    ports:
      - 8000:80

  server:
    image: lolpants/beatsaver-reloaded:server-latest
    build: server
    restart: always
    depends_on:
      - mongo
      - redis
    networks:
      - internal
    volumes:
      - cdn:/home/node/app/cdn:rw
    env_file:
      - .env
    ports:
      - 3000:3000

  docs:
    image: lolpants/beatsaver-reloaded:docs-latest
    build: docs
    restart: always
    ports:
      - 5000:80

networks:
  internal:

volumes:
  cdn:
  mongo:
